### ISSUE TITLE
Problems with build on 3.8

### ISSUE THREAD

**Issue by hnykda** [Blosc/python-blosc#219]
Hi, 

I am trying to get `python-blosc` on Python 3.8 on some of the popular images and I am not really successful. Is there a way how to do it?

For example, on `python:3.8-slim` image, it's impossible, as it wants to build the images, but python-headers are available only for 3.7. Same problem is with ubuntu. I tried to install `libblosc1` and then use `BLOSC_DIR` env variable, but that didn't help. Is there some canonical way how to install that? It feels that it's harder than it should be. 

The common issue I get is `AttributeError: module 'platform' has no attribute 'linux_distribution'`.

**Comment by eamanu** [comment]
@hnykda This seems to be fixed on last release
